version: '3.8'

services:
  backend:
  build: ./backend
  ports:
    - "3000:3000"
  depends_on:
    - database
  environment:
    - MONGO_URI=mongodb://database:27017/myDB

  frontend:
    build: ./frontend
    ports:
     - "4200:80"
    depends_on:
      - backend
  
  database:
    image: mongo
    ports:
     - "27017:27017"